MAIN
	DEFINE f1, f2, f3 INTEGER,
		lb1, lb3, lb5 CHAR

	OPEN WINDOW w1 WITH FORM "0385/0385_slider_step" ATTRIBUTE(BORDER)
		INPUT BY NAME f1, f2, f3
			ON CHANGE f1 DISPLAY f1 TO lb2
			ON CHANGE f2 DISPLAY f2 TO lb4
			ON CHANGE f3 DISPLAY f3 TO lb6
		END INPUT

END MAIN