MAIN
DEFINE f1 INT
LET f1 = 1
OPEN WINDOW mywin AT 1,1 WITH FORM "1805/1805_toolbar_disapper_resize" ATTRIBUTE(BORDER)
 MENU
   COMMAND 'INPUT'
     INPUT BY NAME F1
   COMMAND "Exit"
     EXIT MENU
 END MENU
END MAIN