MAIN
	DEFINE da HASHMAP OF FUNCTION(i INT)
	DEFINE i INT
	LET da[1] = FUNCTION f1
	LET da[2] = FUNCTION f2
	LET da[4] = FUNCTION f4
	FOR i = 1 TO 4
		IF da[i] IS NOT NULL THEN
			CALL da[i]()
			CALL da[i](1)
			CALL da[i](1,2)
		END IF
	END FOR
	DISPLAY "Done"
END MAIN

FUNCTION f1(i INT)
	DISPLAY "f1()"
END FUNCTION

FUNCTION f2(i INT)
	DISPLAY "f2()"
END FUNCTION

FUNCTION f4(i INT)
	DISPLAY "f4()"
END FUNCTION