MAIN

OPEN WINDOW w WITH FORM "3463/3463_main" ATTRIBUTE(BORDER)
--OPEN WINDOW w2 WITH FORM "2" ATTRIBUTE(BORDER)

MENU
COMMAND "create"
  OPEN WINDOW w2 AT 10,10 WITH FORM "3463/3463_parent" ATTRIBUTE(BORDER)
COMMAND "exit"
  EXIT MENU
END MENU

END MAIN