
MAIN
DEFINE kodchp CHAR(5)
DEFINE arr DYNAMIC ARRAY OF INT
OPEN WINDOW w WITH FORM "3725/3725_csp_win"  ATTRIBUTE(BORDER)
INPUT BY NAME kodchp
	ON ACTION "ponuka"
		OPEN WINDOW brows AT 4,28 WITH FORM "3725/3725_csp_win_1" ATTRIBUTE(BORDER)
		DISPLAY ARRAY arr TO sform.* 
		  ON FILL BUFFER
		  			LET arr[1]=1
		  			LET arr[2]=2
		  			LET arr[3]=3
		END DISPLAY
		CLOSE WINDOW brows
END INPUT

END MAIN
