DEFINE colAttributeArr ARRAY[2,5] OF CHAR(12)

MAIN
	DEFINE i SMALLINT
  DEFINE
    inp_char CHAR

	FOR i = 1 TO 5
		LET colAttributeArr[1,i] = i
		LET colAttributeArr[2,i] = i
	END FOR		
	OPEN WINDOW w WITH FORM "4007/4007_gui_demo_issue_2"
  CALL set_count(5)
  CALL displ_tab1()
  WHILE TRUE
    PROMPT "" FOR CHAR inp_char
      ON KEY (F621)
		      CALL set_count(5)
		      CALL displ_tab1()
      ON KEY (F622) 
			  CALL set_count(5)
		      CALL displ_tab2()

    END PROMPT
  END WHILE
END MAIN



FUNCTION displ_tab1()
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc11.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc31.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc51.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc12.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc32.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc52.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc13.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc33.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc53.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc14.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc34.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc54.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc15.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc35.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc55.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc16.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc36.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc56.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc17.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc37.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc57.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc18.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc38.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc58.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc19.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc39.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc59.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc20.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc40.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t01_sc60.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
END FUNCTION
FUNCTION displ_tab2()
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc11.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc31.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc51.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc12.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc32.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc52.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc13.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc33.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc53.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc14.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc34.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc54.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc15.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc35.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc55.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc16.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc36.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc56.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc17.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc37.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc57.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc18.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc38.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc58.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc19.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc39.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc59.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc20.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc40.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
		      DISPLAY ARRAY colAttributeArr[1] TO t02_sc60.* ATTRIBUTE (BLACK, CURRENT ROW DISPLAY = "BLUE") WITHOUT SCROLL
END FUNCTION