#########################################################################################################################################
# Created By: albo (Bondar A.G.)
#########################################################################################################################################
database stores

main

    whenever error continue
    drop table lyc_4090_1
    drop table lyc_4090_2

  sql   --> if the block is commented out, the error compile does not appear !
    create table lyc_4090_1 (
      col_datetime_y_y datetime year TO year,
      col_datetime_y_mo datetime year TO month,
      col_datetime_y_d datetime year TO day,
      col_datetime_y_h datetime year TO hour,
      col_datetime_y_mi datetime year TO minute,
      col_datetime_y_s datetime year TO second,
      col_datetime_y_f datetime year TO fraction(3),
      col_datetime_y_f1 datetime year TO fraction(1),
      col_datetime_y_f2 datetime year TO fraction(2),
      col_datetime_y_f3 datetime year TO fraction(3),
      col_datetime_y_f4 datetime year TO fraction(4),
      col_datetime_y_f5 datetime year TO fraction(5),
      col_datetime_mo_mo datetime month TO month,
      col_datetime_mo_d datetime month TO day,
      col_datetime_mo_h datetime month TO hour,
      col_datetime_mo_mi datetime month TO minute,
      col_datetime_mo_s datetime month TO second,
      col_datetime_mo_f datetime month TO fraction(3),
      col_datetime_mo_f1 datetime month TO fraction(1),
      col_datetime_mo_f2 datetime month TO fraction(2),
      col_datetime_mo_f3 datetime month TO fraction(3),
      col_datetime_mo_f4 datetime month TO fraction(4),
      col_datetime_mo_f5 datetime month TO fraction(5),
      col_datetime_d_d datetime day TO day,
      col_datetime_d_h datetime day TO hour,
      col_datetime_d_mi datetime day TO minute,
      col_datetime_d_s datetime day TO second,
      col_datetime_d_f datetime day TO fraction(3),
      col_datetime_d_f1 datetime day TO fraction(1),
      col_datetime_d_f2 datetime day TO fraction(2),
      col_datetime_d_f3 datetime day TO fraction(3),
      col_datetime_d_f4 datetime day TO fraction(4),
      col_datetime_d_f5 datetime day TO fraction(5),
      col_datetime_h_h datetime hour TO hour,
      col_datetime_h_mi datetime hour TO minute,
      col_datetime_h_s datetime hour TO second,
      col_datetime_h_f datetime hour TO fraction(3),
      col_datetime_h_f1 datetime hour TO fraction(1),
      col_datetime_h_f2 datetime hour TO fraction(2),
      col_datetime_h_f3 datetime hour TO fraction(3),
      col_datetime_h_f4 datetime hour TO fraction(4),
      col_datetime_h_f5 datetime hour TO fraction(5),
      col_datetime_mi_mi datetime minute TO minute,
      col_datetime_mi_s datetime minute TO second,
      col_datetime_mi_f datetime minute TO fraction(3),
      col_datetime_mi_f1 datetime minute TO fraction(1),
      col_datetime_mi_f2 datetime minute TO fraction(2),
      col_datetime_mi_f3 datetime minute TO fraction(3),
      col_datetime_mi_f4 datetime minute TO fraction(4),
      col_datetime_mi_f5 datetime minute TO fraction(5),
      col_datetime_s_s datetime second TO second,
      col_datetime_s_f datetime second TO fraction(3),
      col_datetime_s_f1 datetime second TO fraction(1),
      col_datetime_s_f2 datetime second TO fraction(2),
      col_datetime_s_f3 datetime second TO fraction(3),
      col_datetime_s_f4 datetime second TO fraction(4),
      col_datetime_s_f5 datetime second TO fraction(5),
      col_datetime_f_f datetime fraction TO fraction(3),
      col_datetime_f_f1 datetime fraction TO fraction(1),
      col_datetime_f_f2 datetime fraction TO fraction(2),
      col_datetime_f_f3 datetime fraction TO fraction(3),
      col_datetime_f_f4 datetime fraction TO fraction(4),
      col_datetime_f_f5 datetime fraction TO fraction(5)
    )
  end sql   --> if the block is commented out, the error compile does not appear !
  display "1.  SQLCA.SQLCODE = ",SQLCA.SQLCODE
  
  sql   --> if the block is commented out, the error compile does not appear !
    create table lyc_4090_2 (
      col_interval_y_y interval year TO year,
      col_interval_y1_y interval year(1) TO year,
      col_interval_y9_y interval year(9) TO year,
      col_interval_y_mo interval year TO month,
      col_interval_y1_mo interval year(1) TO month,
      col_interval_y9_mo interval year(9) TO month,
      col_interval_mo_mo interval month TO month,
      col_interval_mo1_mo interval month(1) TO month,
      col_interval_mo9_mo interval month(9) TO month,
      col_interval_d1_d interval day(1) TO day,
      col_interval_d1_h interval day(1) TO hour,
      col_interval_d1_mi interval day(1) TO minute,
      col_interval_d1_s interval day(1) TO second,
      col_interval_d1_f interval day(1) TO fraction(3),
      col_interval_d1_f1 interval day(1) TO fraction(1),
      col_interval_d1_f2 interval day(1) TO fraction(2),
      col_interval_d1_f3 interval day(1) TO fraction(3),
      col_interval_d1_f4 interval day(1) TO fraction(4),
      col_interval_d1_f5 interval day(1) TO fraction(5),
      col_interval_d9_d interval day(9) TO day,
      col_interval_d9_h interval day(9) TO hour,
      col_interval_d9_mi interval day(9) TO minute,
      col_interval_d9_s interval day(9) TO second,
      col_interval_d9_f interval day(9) TO fraction(3),
      col_interval_d9_f1 interval day(9) TO fraction(1),
      col_interval_d9_f2 interval day(9) TO fraction(2),
      col_interval_d9_f3 interval day(9) TO fraction(3),
      col_interval_d9_f4 interval day(9) TO fraction(4),
      col_interval_d9_f5 interval day(9) TO fraction(5),
      col_interval_h1_h interval hour(1) TO hour,
      col_interval_h1_mi interval hour(1) TO minute,
      col_interval_h1_s interval hour(1) TO second,
      col_interval_h1_f interval hour(1) TO fraction(3),
      col_interval_h1_f1 interval hour(1) TO fraction(1),
      col_interval_h1_f2 interval hour(1) TO fraction(2),
      col_interval_h1_f3 interval hour(1) TO fraction(3),
      col_interval_h1_f4 interval hour(1) TO fraction(4),
      col_interval_h1_f5 interval hour(1) TO fraction(5),
      col_interval_h9_h interval hour(9) TO hour,
      col_interval_h9_mi interval hour(9) TO minute,
      col_interval_h9_s interval hour(9) TO second,
      col_interval_h9_f interval hour(9) TO fraction(3),
      col_interval_h9_f1 interval hour(9) TO fraction(1),
      col_interval_h9_f2 interval hour(9) TO fraction(2),
      col_interval_h9_f3 interval hour(9) TO fraction(3),
      col_interval_h9_f4 interval hour(9) TO fraction(4),
      col_interval_h9_f5 interval hour(9) TO fraction(5),
      col_interval_mi1_mi interval minute(1) TO minute,
      col_interval_mi1_s interval minute(1) TO second,
      col_interval_mi1_f interval minute(1) TO fraction(3),
      col_interval_mi1_f1 interval minute(1) TO fraction(1),
      col_interval_mi1_f2 interval minute(1) TO fraction(2),
      col_interval_mi1_f3 interval minute(1) TO fraction(3),
      col_interval_mi1_f4 interval minute(1) TO fraction(4),
      col_interval_mi1_f5 interval minute(1) TO fraction(5),
      col_interval_mi9_mi interval minute(9) TO minute,
      col_interval_mi9_s interval minute(9) TO second,
      col_interval_mi9_f interval minute(9) TO fraction(3),
      col_interval_mi9_f1 interval minute(9) TO fraction(1),
      col_interval_mi9_f2 interval minute(9) TO fraction(2),
      col_interval_mi9_f3 interval minute(9) TO fraction(3),
      col_interval_mi9_f4 interval minute(9) TO fraction(4),
      col_interval_mi9_f5 interval minute(9) TO fraction(5),
      col_interval_s1_s interval second(1) TO second,
      col_interval_s1_f interval second(1) TO fraction(3),
      col_interval_s1_f1 interval second(1) TO fraction(1),
      col_interval_s1_f2 interval second(1) TO fraction(2),
      col_interval_s1_f3 interval second(1) TO fraction(3),
      col_interval_s1_f4 interval second(1) TO fraction(4),
      col_interval_s1_f5 interval second(1) TO fraction(5),
      col_interval_s9_s interval second(9) TO second,
      col_interval_s9_f interval second(9) TO fraction(3),
      col_interval_s9_f1 interval second(9) TO fraction(1),
      col_interval_s9_f2 interval second(9) TO fraction(2),
      col_interval_s9_f3 interval second(9) TO fraction(3),
      col_interval_s9_f4 interval second(9) TO fraction(4),
      col_interval_s9_f5 interval second(9) TO fraction(5),
      col_interval_f_f interval fraction TO fraction(3),
      col_interval_f_f1 interval fraction TO fraction(1),
      col_interval_f_f2 interval fraction TO fraction(2),
      col_interval_f_f3 interval fraction TO fraction(3),
      col_interval_f_f4 interval fraction TO fraction(4),
      col_interval_f_f5 interval fraction TO fraction(5)
    )
  end sql   --> if the block is commented out, the error compile does not appear !   
  display "2.  SQLCA.SQLCODE = ",SQLCA.SQLCODE  
  
end main
  
