#########################################################################################################################################
# Created By: albo (Bondar A.G.)
#########################################################################################################################################
DATABASE 'qexpt_db_test'

MAIN

WHENEVER ANY ERROR CONTINUE

SQL
   DROP ROUTINE IF EXISTS block_demo;
END SQL
DISPLAY "1. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "block_demo.sql"
DISPLAY "2. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS birth_date;
END SQL
DISPLAY "3. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "birth_date.sql"
DISPLAY "4. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS read_address;
END SQL
DISPLAY "5. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "read_address.sql"
DISPLAY "6. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS jvpcontrol_my;
END SQL
DISPLAY "7. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "jvpcontrol_my.sql"
DISPLAY "8. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS genmartdef_my;
END SQL
DISPLAY "9. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "genmartdef_my.sql"
DISPLAY "10. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS scope;
END SQL
DISPLAY "11. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "scope.sql"
DISPLAY "12. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS increase_by_pct;
END SQL
DISPLAY "13. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "increase_by_pct.sql"
DISPLAY "14. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS serial_update;
END SQL
DISPLAY "15. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "serial_update.sql"
DISPLAY "16. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS install_jar_my;
END SQL
DISPLAY "17. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "install_jar_my.sql"
DISPLAY "18. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS cdrcmdproc_my;
END SQL
DISPLAY "19. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "cdrcmdproc_my.sql"
DISPLAY "20. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS updtab;
END SQL
DISPLAY "21. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "updtab.sql"
DISPLAY "22. SQLCA.SQLCODE = ",SQLCA.SQLCODE

SQL
   DROP ROUTINE IF EXISTS proc1;
END SQL
DISPLAY "23. SQLCA.SQLCODE = ",SQLCA.SQLCODE

CREATE PROCEDURE FROM "proc1.sql"
DISPLAY "24. SQLCA.SQLCODE = ",SQLCA.SQLCODE

END MAIN
