MAIN
DEFINE arr dynamic array of int
DEFINE i INT
OPEN WINDOW w WITH FORM "4100/4100_display_arr_count_limit" ATTRIBUTE (BORDER)
WHILE TRUE
DISPLAY ARRAY arr to arr.* ATTRIBUTES (COUNT=4)
	ON FILL BUFFER
		FOR i=1 to 5
			LET arr[i]=i
		END FOR
	ON ACTION REFRESH
		EXIT DISPLAY
	ON ACTION EXIT
		EXIT PROGRAM
END DISPLAY 
END WHILE
END MAIN