MAIN
DEFINE f1,f2,f3 STRING
	LET f1="value_1"
	LET f2="value_1"
	LET f3="value_1"
	OPEN WINDOW w WITH FORM "4356/4356_null_combo_lostbox_radio" ATTRIBUTE(BORDER)
	INPUT BY NAME f1,f2,f3 WITHOUT DEFAULTS
	IF f1 IS NULL THEN
		DISPLAY "COMBOBOX IS NULL"
	END IF
	IF f2 IS NULL THEN
		DISPLAY "RADIO IS NULL"
	END IF
	IF f3 IS NULL THEN
		DISPLAY "LISTBOX IS NULL"
	END IF
	CALL fgl_getkey()
END MAIN