MAIN
DEFINE tarr DYNAMIC ARRAY OF INT
DEFINE i INT

FOR i=1 TO 100
	LET tarr[i]=i
END FOR

OPEN WINDOW w WITH FORM "4366/4366_table_row_focus" ATTRIBUTE(BORDER)
	WHILE TRUE
		CALL fgl_getkey()
		DISPLAY ARRAY tarr TO rootContainer.*
		CLEAR FORM
	END WHILE
END MAIN