MAIN
  DEFINE tarr DYNAMIC ARRAY OF INT
  LET tarr[1]="1"
  LET tarr[2]="2"
  LET tarr[3]="3"
  OPEN WINDOW w WITH FORM "4428/4428_table_default_actions" ATTRIBUTE(BORDER)

  DISPLAY ARRAY tarr TO rootcontainer.*
  	ON ACTION "DELETE"
  		DISPLAY "DELETE" 
  	ON ACTION "APPEND"
  		DISPLAY "APPEND" 
  	ON ACTION "INSERT"
  		DISPLAY "INSERT"
  END DISPLAY 


  INPUT ARRAY tarr FROM rootcontainer.* ATTRIBUTE(WITHOUT DEFAULTS)
  	ON ACTION "DELETE"
  		DISPLAY "DELETE" 
  	ON ACTION "APPEND"
  		DISPLAY "APPEND" 
  	ON ACTION "INSERT"
  		DISPLAY "INSERT"
  END INPUT 
END MAIN	
