MAIN
	OPEN WINDOW w AT 1,1 WITH 20 ROWS, 80 COLUMNS
	MENU
		ON ACTION "zzz1"
		ON ACTION "zzz2"
		ON ACTION "zzz3"
		ON ACTION "zzz4"
		ON ACTION "zzz5"
		ON ACTION "zzz6"
		ON ACTION "zzz7"
		ON ACTION "zzz8"
		ON ACTION "zzz9"
		ON ACTION "zzz10"
		ON ACTION "zzz11"
		ON ACTION "zzz12"
		ON ACTION "zzz13"
		ON ACTION "zzz14"
		ON ACTION "zzz15"
		ON ACTION "zzz16"
		ON ACTION "zzz17"
		ON ACTION "zzz18"
		ON ACTION "EEEEXIT"
			EXIT MENU
	END MENU
END MAIN