MAIN
DEFINE s3 DYNAMIC ARRAY OF RECORD f1,f2,f3 STRING END RECORD
DEFINE i INT

OPEN WINDOW w WITH FORM "4616/4616_setfieldactive_column" ATTRIBUTE(BORDER)
FOR i=1 TO 10
	LET s3[i].f1="col1_",trim(i)
	LET s3[i].f2="col2_",trim(i)
	LET s3[i].f3="col3_",trim(i)
END FOR

INPUT ARRAY s3 FROM zz.* ATTRIBUTE(WITHOUT DEFAULTS)
	BEFORE INPUT
		CALL DIALOG.SetFieldActive("f1", FALSE)
END INPUT

END MAIN