
MAIN
 DEFINE i1 DYNAMIC ARRAY OF SMALLFLOAT
 DEFINE i2 DYNAMIC ARRAY OF SMALLFLOAT

	WHENEVER ANY ERROR CONTINUE
	CALL ret() RETURNING i1
	CALL chsck_arr(i1)
	DISPLAY "###################"
	LET i2=ret() 
	CALL chsck_arr(i2)
END MAIN


FUNCTION ret()
  DEFINE arr DYNAMIC ARRAY OF SMALLFLOAT
	LET arr[1]="1"
	LET arr[2]="2"
	RETURN arr
END FUNCTION

FUNCTION chsck_arr(arr1)
  DEFINE arr1 DYNAMIC ARRAY OF SMALLFLOAT

	DISPLAY arr1
	
	IF arr1[1] is null THEN DISPLAY "1NULL"
	ELSE DISPLAY "1NOT NULL" END IF
	
	IF arr1[2] is null THEN DISPLAY "2NULL"
	ELSE DISPLAY "2NOT NULL" END IF
	
	IF arr1[3] is null THEN DISPLAY "3NULL"
	ELSE DISPLAY "3NOT NULL" END IF
END FUNCTION