MAIN
DEFINE tarr DYNAMIC ARRAY OF CHAR(20)
DEFINE i INT
	FOR i=1 TO 100
		LET tarr[i]=i
	END FOR
	OPEN WINDOW w WITH FORM "5087/5087_table_content_update" ATTRIBUTE(BORDER)
	MENU
		COMMAND "input"
			INPUT ARRAY tarr FROM tarr.* ATTRIBUTE(WITHOUT DEFAULTS)
		COMMAND "display"
			DISPLAY ARRAY tarr TO tarr.*
	END MENU
END MAIN