MAIN
DEFINE tarr DYNAMIC ARRAY OF RECORD f1,f2,f3 CHAR(30) END RECORD
	OPEN WINDOW w WITH FORM "5940/5940_popup_error_table" ATTRIBUTE(BORDER)
	INPUT ARRAY tarr FROM tarr.*
		AFTER FIELD f2 
			ERROR "error"
			NEXT FIELD f2
	END INPUT
END MAIN
