MAIN
DEFINE tarr DYNAMIC ARRAY OF RECORD f1,f2 CHAR(20) END RECORD
DEFINE i INT
	OPEN WINDOW w WITH FORM "5960/5960_arr_curr_val_zero"
	LET tarr[1].f1=1
	INPUT ARRAY tarr WITHOUT DEFAULTS FROM record1.* ATTRIBUTE(UNBUFFERED) 
		BEFORE ROW 
			LET i=arr_curr()
			DISPLAY "arr_cur: ",i
		AFTER INPUT
			NEXT FIELD f1
	END INPUT
END MAIN
