MAIN
	DEFINE tarr DYNAMIC ARRAY OF RECORD 
		f1 CHAR(30),
		f2 CHAR(30)
	END RECORD 
	LET tarr[1].f1=1
	LET tarr[2].f1=2
	OPTIONS FIELD ORDER UNCONSTRAINED 
	
	OPEN WINDOW w WITH FORM "6082/6082_tabindex_unconstrained"	
	INPUT ARRAY tarr WITHOUT DEFAULTS FROM sr_orderdetl.*
		BEFORE FIELD line_num DISPLAY "BEFORE FIELD"
		AFTER FIELD line_num DISPLAY "AFTER FIELD"
	END INPUT 
 END MAIN
