MAIN
DEFINE f1,f2,f3,f4 CHAR(5)
OPEN WINDOW w WITH FORM "6096/6096_disable_first_field"
INPUT BY NAME f1,f2,f3,f4
	BEFORE INPUT
		CALL Dialog.setFieldActive("f1",FALSE)
		CALL Dialog.setFieldActive("f3",FALSE)
	BEFORE FIELD f1
		DISPLAY "BEFORE FIELD f1"
	BEFORE FIELD f2
		DISPLAY "BEFORE FIELD f2"
	BEFORE FIELD f3
		DISPLAY "BEFORE FIELD f3"
	BEFORE FIELD f4
		DISPLAY "BEFORE FIELD f4"
	AFTER FIELD f1
		DISPLAY "AFTER FIELD f1"
	AFTER FIELD f2
		DISPLAY "AFTER FIELD f2"
	AFTER FIELD f3
		DISPLAY "AFTER FIELD f3"
	AFTER FIELD f4
		DISPLAY "AFTER FIELD f4"
END INPUT
END MAIN
