GLOBALS 

	DEFINE glob_rec_prog RECORD
		module_id VARCHAR(5),
		prog_id VARCHAR(5)
		END RECORD 
	DEFINE glob_rec_settings RECORD 
		reportPath STRING, 
		logPath STRING,
		logFile STRING,
		saveUnbalancedBatch BOOLEAN, 
		maxListArraySize SMALLINT,
		maxListArraySizeSwitch SMALLINT,
		maxComboListSize SMALLINT, 
		maxchildlaunch SMALLINT,
		hideDeletedCustomers BOOLEAN,
		default_country_code BOOLEAN,
		default_currency_code BOOLEAN,
		default_language BOOLEAN,
		default_state BOOLEAN,
		maxReportHistorySize BIGINT
	END RECORD 
	DEFINE g_rec_yes RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD
	
	DEFINE g_rec_no RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD	
	CONSTANT RPT_SHOW_RMS_DIALOG BOOLEAN = TRUE
	CONSTANT RPT_HIDE_RMS_DIALOG BOOLEAN = FALSE
	
	CONSTANT ASCII_FORM_FEED SMALLINT = 12
	CONSTANT ASCII_QUOTATION_MARK SMALLINT = 34	

	CONSTANT DIR_FORWARD boolean = TRUE
	CONSTANT DIR_BACKWARD boolean = FALSE
	
	---------------------------------------------------
	CONSTANT filter_on boolean = true 
	CONSTANT filter_off boolean = false 

	CONSTANT filter_query_off SMALLINT = 0 
	CONSTANT filter_query_on SMALLINT = 1 
	CONSTANT filter_query_select SMALLINT = 2 
	CONSTANT filter_query_where SMALLINT = 3 

	CONSTANT filter_where_all STRING = " 1=1 " 
	CONSTANT ret_normal SMALLINT = 0 
	CONSTANT ret_cancel SMALLINT = -1 

	CONSTANT MODE_SELECT SMALLINT = 0
	CONSTANT MODE_INSERT SMALLINT = 1 
	CONSTANT MODE_UPDATE SMALLINT = 2 
	CONSTANT MODE_DELETE SMALLINT = 3 
	CONSTANT MODE_FIND SMALLINT = 4  
	CONSTANT MODE_CLASSIC_VIEW STRING = "VIEW"
	CONSTANT MODE_CLASSIC_ADD STRING = "ADD"
	CONSTANT MODE_CLASSIC_EDIT STRING = "EDIT" 
	CONSTANT MODE_CLASSIC_REMOVE STRING = "REMOVE"
	CONSTANT MODE_CLASSIC_MODIFY STRING = "MODIFY"	
	CONSTANT MODE_CLASSIC_INSERT STRING = "INSERT" 
	CONSTANT MODE_CLASSIC_UPDATE STRING = "UPDATE" 
	CONSTANT MODE_CLASSIC_DELETE STRING = "DELETE" 
	CONSTANT MODE_CLASSIC_SELECT STRING = "SELECT"	
	CONSTANT MODE_CLASSIC_FIND STRING = "FIND"  
	CONSTANT MODE_CLASSIC1_VIEW STRING = "V"
	CONSTANT MODE_CLASSIC1_ADD STRING = "A"
	CONSTANT MODE_CLASSIC1_EDIT STRING = "E" 
	CONSTANT MODE_CLASSIC1_REMOVE STRING = "R"
	CONSTANT MODE_CLASSIC1_MODIFY STRING = "M"	
	CONSTANT MODE_CLASSIC1_INSERT STRING = "I" 
	CONSTANT MODE_CLASSIC1_UPDATE STRING = "U" 
	CONSTANT MODE_CLASSIC1_DELETE STRING = "D" 
	CONSTANT MODE_CLASSIC1_SELECT STRING = "S"	
	CONSTANT MODE_CLASSIC1_FIND STRING = "F"  
	
	CONSTANT UI_OFF SMALLINT = 0 
	CONSTANT UI_ON SMALLINT = 1 
	CONSTANT UI_PK SMALLINT = 2
	CONSTANT UI_FK SMALLINT = 3

	CONSTANT UI_CONFIRM_OFF BOOLEAN = FALSE 
	CONSTANT UI_CONFIRM_ON BOOLEAN = TRUE 
	CONSTANT COA_ACCOUNT_REQUIRED_can_be_normal_transaction SMALLINT = "1" 
	CONSTANT COA_ACCOUNT_REQUIRED_can_be_control_bank SMALLINT = "2" 
	CONSTANT COA_ACCOUNT_REQUIRED_can_be_control_other SMALLINT = "3" 
	CONSTANT COA_ACCOUNT_REQUIRED_is_control_bank SMALLINT = "4" 

	CONSTANT COMBO_FIRST_ARG_IS_VALUE SMALLINT = 0 
	CONSTANT COMBO_first_ARG_is_LABEL SMALLINT = 1 

	CONSTANT COMBO_SORT_by_VALUE SMALLINT = 0 
	CONSTANT COMBO_SORT_BY_LABEL SMALLINT = 1 

	CONSTANT COMBO_VALUE_AND_LABEL SMALLINT = 0 
	CONSTANT COMBO_VALUE_is_LABEL SMALLINT = 1 

	CONSTANT COMBO_LABEL_IS_LABEL SMALLINT = 0 
	CONSTANT COMBO_LABEL_IS_VALUE_TAB_LABEL SMALLINT = 1 
	CONSTANT COMBO_LABEL_IS_LABEL_BRACE_VALUE SMALLINT = 2 
	CONSTANT COMBO_LABEL_IS_VALUE_DASH_LABEL SMALLINT = 3 

	CONSTANT COMBO_NULL_NOT SMALLINT = 0 
	CONSTANT COMBO_NULL_SPACE SMALLINT = 1 
	CONSTANT COMBO_NULL_NONE SMALLINT = 2 
	CONSTANT COMBO_NULL_NA SMALLINT = 3 
	CONSTANT COMBO_NULL_UD SMALLINT = 4
	CONSTANT COMBO_NULL_NOT_ON_HOLD SMALLINT = 5
	CONSTANT COMBO_NULL_NOT_USED SMALLINT = 6
	CONSTANT COMBO_NULL_ANY SMALLINT = 7
	DEFINE session_info RECORD 
		sid INTEGER,
		user_name char(32),
 		pid INTEGER, 
		login_timestamp DATETIME year TO second ,
		database_name CHAR(128)
	END RECORD 

	DEFINE error_retry_nbr SMALLINT 
	DEFINE continue_program_on_error BOOLEAN
	DEFINE custom_error_message STRING
	DEFINE g_default_isolation_mode CHAR(64)

	DEFINE lol1_glob_rec_prog RECORD
		module_id VARCHAR(5),
		prog_id VARCHAR(5)
		END RECORD 
	DEFINE lol1_glob_rec_settings RECORD 
		reportPath STRING, 
		logPath STRING,
		logFile STRING,
		saveUnbalancedBatch BOOLEAN, 
		maxListArraySize SMALLINT,
		maxListArraySizeSwitch SMALLINT,
		maxComboListSize SMALLINT, 
		maxchildlaunch SMALLINT,
		hideDeletedCustomers BOOLEAN,
		default_country_code BOOLEAN,
		default_currency_code BOOLEAN,
		default_language BOOLEAN,
		default_state BOOLEAN,
		maxReportHistorySize BIGINT
	END RECORD 
	DEFINE lol1_g_rec_yes RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD
	
	DEFINE lol1_g_rec_no RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD	
	CONSTANT lol1_RPT_SHOW_RMS_DIALOG BOOLEAN = TRUE
	CONSTANT lol1_RPT_HIDE_RMS_DIALOG BOOLEAN = FALSE
	
	CONSTANT lol1_ASCII_FORM_FEED SMALLINT = 12
	CONSTANT lol1_ASCII_QUOTATION_MARK SMALLINT = 34	

	CONSTANT lol1_DIR_FORWARD boolean = TRUE
	CONSTANT lol1_DIR_BACKWARD boolean = FALSE
	
	---------------------------------------------------
	CONSTANT lol1_filter_on boolean = true 
	CONSTANT lol1_filter_off boolean = false 

	CONSTANT lol1_filter_query_off SMALLINT = 0 
	CONSTANT lol1_filter_query_on SMALLINT = 1 
	CONSTANT lol1_filter_query_select SMALLINT = 2 
	CONSTANT lol1_filter_query_where SMALLINT = 3 

	CONSTANT lol1_filter_where_all STRING = " 1=1 " 
	CONSTANT lol1_ret_normal SMALLINT = 0 
	CONSTANT lol1_ret_cancel SMALLINT = -1 

	CONSTANT lol1_MODE_SELECT SMALLINT = 0
	CONSTANT lol1_MODE_INSERT SMALLINT = 1 
	CONSTANT lol1_MODE_UPDATE SMALLINT = 2 
	CONSTANT lol1_MODE_DELETE SMALLINT = 3 
	CONSTANT lol1_MODE_FIND SMALLINT = 4  
	CONSTANT lol1_MODE_CLASSIC_VIEW STRING = "VIEW"
	CONSTANT lol1_MODE_CLASSIC_ADD STRING = "ADD"
	CONSTANT lol1_MODE_CLASSIC_EDIT STRING = "EDIT" 
	CONSTANT lol1_MODE_CLASSIC_REMOVE STRING = "REMOVE"
	CONSTANT lol1_MODE_CLASSIC_MODIFY STRING = "MODIFY"	
	CONSTANT lol1_MODE_CLASSIC_INSERT STRING = "INSERT" 
	CONSTANT lol1_MODE_CLASSIC_UPDATE STRING = "UPDATE" 
	CONSTANT lol1_MODE_CLASSIC_DELETE STRING = "DELETE" 
	CONSTANT lol1_MODE_CLASSIC_SELECT STRING = "SELECT"	
	CONSTANT lol1_MODE_CLASSIC_FIND STRING = "FIND"  
	CONSTANT lol1_MODE_CLASSIC1_VIEW STRING = "V"
	CONSTANT lol1_MODE_CLASSIC1_ADD STRING = "A"
	CONSTANT lol1_MODE_CLASSIC1_EDIT STRING = "E" 
	CONSTANT lol1_MODE_CLASSIC1_REMOVE STRING = "R"
	CONSTANT lol1_MODE_CLASSIC1_MODIFY STRING = "M"	
	CONSTANT lol1_MODE_CLASSIC1_INSERT STRING = "I" 
	CONSTANT lol1_MODE_CLASSIC1_UPDATE STRING = "U" 
	CONSTANT lol1_MODE_CLASSIC1_DELETE STRING = "D" 
	CONSTANT lol1_MODE_CLASSIC1_SELECT STRING = "S"	
	CONSTANT lol1_MODE_CLASSIC1_FIND STRING = "F"  
	
	CONSTANT lol1_UI_OFF SMALLINT = 0 
	CONSTANT lol1_UI_ON SMALLINT = 1 
	CONSTANT lol1_UI_PK SMALLINT = 2
	CONSTANT lol1_UI_FK SMALLINT = 3

	CONSTANT lol1_UI_CONFIRM_OFF BOOLEAN = FALSE 
	CONSTANT lol1_UI_CONFIRM_ON BOOLEAN = TRUE 
	CONSTANT lol1_COA_ACCOUNT_REQUIRED_can_be_normal_transaction SMALLINT = "1" 
	CONSTANT lol1_COA_ACCOUNT_REQUIRED_can_be_control_bank SMALLINT = "2" 
	CONSTANT lol1_COA_ACCOUNT_REQUIRED_can_be_control_other SMALLINT = "3" 
	CONSTANT lol1_COA_ACCOUNT_REQUIRED_is_control_bank SMALLINT = "4" 

	CONSTANT lol1_COMBO_FIRST_ARG_IS_VALUE SMALLINT = 0 
	CONSTANT lol1_COMBO_first_ARG_is_LABEL SMALLINT = 1 

	CONSTANT lol1_COMBO_SORT_by_VALUE SMALLINT = 0 
	CONSTANT lol1_COMBO_SORT_BY_LABEL SMALLINT = 1 

	CONSTANT lol1_COMBO_VALUE_AND_LABEL SMALLINT = 0 
	CONSTANT lol1_COMBO_VALUE_is_LABEL SMALLINT = 1 

	CONSTANT lol1_COMBO_LABEL_IS_LABEL SMALLINT = 0 
	CONSTANT lol1_COMBO_LABEL_IS_VALUE_TAB_LABEL SMALLINT = 1 
	CONSTANT lol1_COMBO_LABEL_IS_LABEL_BRACE_VALUE SMALLINT = 2 
	CONSTANT lol1_COMBO_LABEL_IS_VALUE_DASH_LABEL SMALLINT = 3 

	CONSTANT lol1_COMBO_NULL_NOT SMALLINT = 0 
	CONSTANT lol1_COMBO_NULL_SPACE SMALLINT = 1 
	CONSTANT lol1_COMBO_NULL_NONE SMALLINT = 2 
	CONSTANT lol1_COMBO_NULL_NA SMALLINT = 3 
	CONSTANT lol1_COMBO_NULL_UD SMALLINT = 4
	CONSTANT lol1_COMBO_NULL_NOT_ON_HOLD SMALLINT = 5
	CONSTANT lol1_COMBO_NULL_NOT_USED SMALLINT = 6
	CONSTANT lol1_COMBO_NULL_ANY SMALLINT = 7
	DEFINE lol1_session_info RECORD 
		sid INTEGER,
		user_name char(32),
 		pid INTEGER, 
		login_timestamp DATETIME year TO second ,
		database_name CHAR(128)
	END RECORD 

	DEFINE lol1_error_retry_nbr SMALLINT 
	DEFINE lol1_continue_program_on_error BOOLEAN
	DEFINE lol1_custom_error_message STRING
	DEFINE lol1_g_default_isolation_mode CHAR(64)

	DEFINE lol1_glob_rec_prog RECORD
		module_id VARCHAR(5),
		prog_id VARCHAR(5)
		END RECORD 
	DEFINE lol2_lol1_glob_rec_settings RECORD 
		reportPath STRING, 
		logPath STRING,
		logFile STRING,
		saveUnbalancedBatch BOOLEAN, 
		maxListArraySize SMALLINT,
		maxListArraySizeSwitch SMALLINT,
		maxComboListSize SMALLINT, 
		maxchildlaunch SMALLINT,
		hideDeletedCustomers BOOLEAN,
		default_country_code BOOLEAN,
		default_currency_code BOOLEAN,
		default_language BOOLEAN,
		default_state BOOLEAN,
		maxReportHistorySize BIGINT
	END RECORD 
	DEFINE lol2_lol1_g_rec_yes RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD
	
	DEFINE lol2_lol1_g_rec_no RECORD
		english_val CHAR(1),
		localized_val CHAR(1)
	END RECORD	
	CONSTANT lol2_lol1_RPT_SHOW_RMS_DIALOG BOOLEAN = TRUE
	CONSTANT lol2_lol1_RPT_HIDE_RMS_DIALOG BOOLEAN = FALSE
	
	CONSTANT lol2_lol1_ASCII_FORM_FEED SMALLINT = 12
	CONSTANT lol2_lol1_ASCII_QUOTATION_MARK SMALLINT = 34	

	CONSTANT lol2_lol1_DIR_FORWARD boolean = TRUE
	CONSTANT lol2_lol1_DIR_BACKWARD boolean = FALSE
	
	---------------------------------------------------
	CONSTANT lol2_lol1_filter_on boolean = true 
	CONSTANT lol2_lol1_filter_off boolean = false 

	CONSTANT lol2_lol1_filter_query_off SMALLINT = 0 
	CONSTANT lol2_lol1_filter_query_on SMALLINT = 1 
	CONSTANT lol2_lol1_filter_query_select SMALLINT = 2 
	CONSTANT lol2_lol1_filter_query_where SMALLINT = 3 

	CONSTANT lol2_lol1_filter_where_all STRING = " 1=1 " 
	CONSTANT lol2_lol1_ret_normal SMALLINT = 0 
	CONSTANT lol2_lol1_ret_cancel SMALLINT = -1 

	CONSTANT lol2_lol1_MODE_SELECT SMALLINT = 0
	CONSTANT lol2_lol1_MODE_INSERT SMALLINT = 1 
	CONSTANT lol2_lol1_MODE_UPDATE SMALLINT = 2 
	CONSTANT lol2_lol1_MODE_DELETE SMALLINT = 3 
	CONSTANT lol2_lol1_MODE_FIND SMALLINT = 4  
	CONSTANT lol2_lol1_MODE_CLASSIC_VIEW STRING = "VIEW"
	CONSTANT lol2_lol1_MODE_CLASSIC_ADD STRING = "ADD"
	CONSTANT lol2_lol1_MODE_CLASSIC_EDIT STRING = "EDIT" 
	CONSTANT lol2_lol1_MODE_CLASSIC_REMOVE STRING = "REMOVE"
	CONSTANT lol2_lol1_MODE_CLASSIC_MODIFY STRING = "MODIFY"	
	CONSTANT lol2_lol1_MODE_CLASSIC_INSERT STRING = "INSERT" 
	CONSTANT lol2_lol1_MODE_CLASSIC_UPDATE STRING = "UPDATE" 
	CONSTANT lol2_lol1_MODE_CLASSIC_DELETE STRING = "DELETE" 
	CONSTANT lol2_lol1_MODE_CLASSIC_SELECT STRING = "SELECT"	
	CONSTANT lol2_lol1_MODE_CLASSIC_FIND STRING = "FIND"  
	CONSTANT lol2_lol1_MODE_CLASSIC1_VIEW STRING = "V"
	CONSTANT lol2_lol1_MODE_CLASSIC1_ADD STRING = "A"
	CONSTANT lol2_lol1_MODE_CLASSIC1_EDIT STRING = "E" 
	CONSTANT lol2_lol1_MODE_CLASSIC1_REMOVE STRING = "R"
	CONSTANT lol2_lol1_MODE_CLASSIC1_MODIFY STRING = "M"	
	CONSTANT lol2_lol1_MODE_CLASSIC1_INSERT STRING = "I" 
	CONSTANT lol2_lol1_MODE_CLASSIC1_UPDATE STRING = "U" 
	CONSTANT lol2_lol1_MODE_CLASSIC1_DELETE STRING = "D" 
	CONSTANT lol2_lol1_MODE_CLASSIC1_SELECT STRING = "S"	
	CONSTANT lol2_lol1_MODE_CLASSIC1_FIND STRING = "F"  
	
	CONSTANT lol2_lol1_UI_OFF SMALLINT = 0 
	CONSTANT lol2_lol1_UI_ON SMALLINT = 1 
	CONSTANT lol2_lol1_UI_PK SMALLINT = 2
	CONSTANT lol2_lol1_UI_FK SMALLINT = 3

	CONSTANT lol2_lol1_UI_CONFIRM_OFF BOOLEAN = FALSE 
	CONSTANT lol2_lol1_UI_CONFIRM_ON BOOLEAN = TRUE 
	CONSTANT lol2_lol1_COA_ACCOUNT_REQUIRED_can_be_normal_transaction SMALLINT = "1" 
	CONSTANT lol2_lol1_COA_ACCOUNT_REQUIRED_can_be_control_bank SMALLINT = "2" 
	CONSTANT lol2_lol1_COA_ACCOUNT_REQUIRED_can_be_control_other SMALLINT = "3" 
	CONSTANT lol2_lol1_COA_ACCOUNT_REQUIRED_is_control_bank SMALLINT = "4" 

	CONSTANT lol2_lol1_COMBO_FIRST_ARG_IS_VALUE SMALLINT = 0 
	CONSTANT lol2_lol1_COMBO_first_ARG_is_LABEL SMALLINT = 1 

	CONSTANT lol2_lol1_COMBO_SORT_by_VALUE SMALLINT = 0 
	CONSTANT lol2_lol1_COMBO_SORT_BY_LABEL SMALLINT = 1 

	CONSTANT lol2_lol1_COMBO_VALUE_AND_LABEL SMALLINT = 0 
	CONSTANT lol2_lol1_COMBO_VALUE_is_LABEL SMALLINT = 1 

	CONSTANT lol2_lol1_COMBO_LABEL_IS_LABEL SMALLINT = 0 
	CONSTANT lol2_lol1_COMBO_LABEL_IS_VALUE_TAB_LABEL SMALLINT = 1 
	CONSTANT lol2_lol1_COMBO_LABEL_IS_LABEL_BRACE_VALUE SMALLINT = 2 
	CONSTANT lol2_lol1_COMBO_LABEL_IS_VALUE_DASH_LABEL SMALLINT = 3 

	CONSTANT lol2_lol1_COMBO_NULL_NOT SMALLINT = 0 
	CONSTANT lol2_lol1_COMBO_NULL_SPACE SMALLINT = 1 
	CONSTANT lol2_lol1_COMBO_NULL_NONE SMALLINT = 2 
	CONSTANT lol2_lol1_COMBO_NULL_NA SMALLINT = 3 
	CONSTANT lol2_lol1_COMBO_NULL_UD SMALLINT = 4
	CONSTANT lol2_lol1_COMBO_NULL_NOT_ON_HOLD SMALLINT = 5
	CONSTANT lol2_lol1_COMBO_NULL_NOT_USED SMALLINT = 6
	CONSTANT lol2_lol1_COMBO_NULL_ANY SMALLINT = 7
	DEFINE lol2_lol1_session_info RECORD 
		sid INTEGER,
		user_name char(32),
 		pid INTEGER, 
		login_timestamp DATETIME year TO second ,
		database_name CHAR(128)
	END RECORD 

	DEFINE lol2_lol1_error_retry_nbr SMALLINT 
	DEFINE lol2_lol1_continue_program_on_error BOOLEAN
	DEFINE lol2_lol1_custom_error_message STRING
	DEFINE lol2_lol1_g_default_isolation_mode CHAR(64)

END GLOBALS 

