GLOBALS
   WHENEVER SQL ERROR CALL err_func	
END GLOBALS

MAIN
	SELECT * FROM table_not_exist
	OPEN WINDOW w WITH FORM "not_exist"
	


END MAIN

FUNCTION err_func()
	DISPLAY "Beeep! ",STATUS,"|",STATUS,SQLCA.SQLCODE
END FUNCTION