MAIN
 DEFINE f1,f2 STRING
	OPEN WINDOW w WITH FORM "6320/6320_next_field_in_function" ATTRIBUTE(BORDER)
	INPUT BY NAME f1,f2
		ON ACTION moveToF2
			CALL nextField()
	END INPUT
END MAIN

FUNCTION nextField()
	NEXT FIELD f2
END FUNCTION