MAIN
	DEFINE f1,f2 CHAR(5)
	DEFINE tarr ARRAY[2] OF CHAR(5)
	OPEN WINDOW w WITH FORM "6710/6710_static_arr_focus_dialog" ATTRIBUTE(BORDER)
	CALL SET_COUNT(2)
	DIALOG
		INPUT BY NAME f1
		END INPUT
		INPUT ARRAY tarr FROM tarr.*
		END INPUT
		INPUT BY NAME f2
		END INPUT
		ON ACTION EXIT 
			EXIT DIALOG
	END DIALOG
	
END MAIN 