MAIN
	DEFINE f1,f2 CHAR(5)
	DEFINE tarr DYNAMIC ARRAY OF CHAR(5)
	OPEN WINDOW w WITH FORM "6712/6712_no_append_table" ATTRIBUTE(BORDER)
		INPUT ARRAY tarr FROM tarr.* ATTRIBUTE(AUTO APPEND = FALSE)
		END INPUT
	
END MAIN 