MAIN
	DEFINE f1,f2 CHAR(5)
	DEFINE tarr DYNAMIC ARRAY OF CHAR(5)
	OPEN WINDOW w WITH FORM "6720/6720_dialog_table_autoappend_false" ATTRIBUTE(BORDER)
	DIALOG
		INPUT BY NAME f1
		END INPUT
	
		INPUT ARRAY tarr FROM tarr.* ATTRIBUTE(AUTO APPEND = FALSE)
		END INPUT
		
		ON ACTION EXIT 
			EXIT DIALOG
	END DIALOG		
END MAIN 