MAIN
	OPEN WINDOW form1_page AT 1,1 WITH 14 ROWS, 78 COLUMNS
	OPEN FORM form1_form FROM "7181/7181_form_child"
	DISPLAY FORM form1_form
	DISPLAY "child" AT 1,1
	MENU
	COMMAND "EXIT"
		EXIT MENU
	END MENU
END MAIN