MAIN
	CALL fgl_putenv("QX_COMPAT=Informix4GL")
	OPEN WINDOW w AT 5,5 WITH 20 ROWS, 20 COLUMNS ATTRIBUTE(BORDER)
	MENU
		COMMAND "exit"
			EXIT MENU
	END MENU
	CLOSE WINDOW W
	OPEN WINDOW w AT 5,5 WITH FORM "7192/7192_border_i4gl" ATTRIBUTE(BORDER)
	MENU
		COMMAND "exit"
			EXIT MENU
	END MENU
	CLOSE WINDOW W
END MAIN