MAIN
	CALL fgl_putenv("QX_COMPAT=Informix4GL")
	OPEN WINDOW w AT 5,5 WITH 20 ROWS, 35 COLUMNS ATTRIBUTE(BORDER,style="dialog")
	MENU
		COMMAND "exit"
			EXIT MENU
	END MENU
	CLOSE WINDOW W
	OPEN WINDOW w AT 5,5 WITH FORM "7193/7193_border_dialog_i4gl" ATTRIBUTE(BORDER,style="dialog")
	MENU
		COMMAND "exit"
			EXIT MENU
	END MENU
	CLOSE WINDOW W
END MAIN