MAIN
	CALL fgl_putenv("QX_COMPAT=Informix4GL")
	OPEN WINDOW win1 WITH FORM "7249/7249_grid" ATTRIBUTE(WHITE)
	OPEN WINDOW win2 WITH FORM "7249/7249_coord" ATTRIBUTE(WHITE)
	CALL fgl_getkey()
 
END MAIN