MAIN
 DEFINE f1,f2,f3 STRING
OPEN WINDOW w WITH FORM "7327/7327_functionField_action_infield" ATTRIBUTE(BORDER)
			INPUT BY NAME f1,f2,f3 WITHOUT DEFAULTS ATTRIBUTE(UNBUFFERED)
				ON ACTION "HIDE ACTION" INFIELD(f1)
				ON ACTION "LOOKUP_CUST" INFIELD(f2)
					DISPLAY "f1"
				ON ACTION "LOOKUP_CUST" INFIELD(f3)
					DISPLAY "f2"
			END INPUT

END MAIN
