MAIN
 DEFINE f1,f2,f3 STRING
OPEN WINDOW w WITH FORM "7422/7422_ff_action_cursor" ATTRIBUTE(BORDER)
			INPUT BY NAME f1,f2,f3 WITHOUT DEFAULTS 
				AFTER FIELD f1
				  NEXT FIELD f1
				ON ACTION "LOOKUP_CUST"
					DISPLAY "FF button f2"
			END INPUT

END MAIN
