MAIN
  DEFINE rec RECORD f1,f2,f3,f4,f5,f6,f7,f8 STRING END RECORD
	OPEN WINDOW w WITH FORM "7495/7495_complex_widget_focus" ATTRIBUTE(BORDER)
	INPUT BY NAME rec.*
		AFTER FIELD f1
			NEXT FIELD f1
	END INPUT
END MAIN