MAIN
DEFINE f1,f2 STRING
	OPEN WINDOW w WITH FORM "7554/7554_tf_ta_symb" ATTRIBUTE(BORDER)
	MENU
		ON ACTION "exit"
			EXIT MENU
		ON ACTION "show"
			DISPLAY "!" TO f1
			DISPLAY "*" TO f2
	END MENU
END MAIN