MAIN
DEFINE f1,f2,f3 INT
OPTIONS INPUT wrap
	OPEN WINDOW w WITH FORM "7562/7562_nextfield_prev" ATTRIBUTE(BORDER)


INPUT BY NAME f1,f2, f3
BEFORE FIELD f1 DISPLAY "BEFORE FIELD f1"
BEFORE FIELD f3 DISPLAY "BEFORE FIELD f3"
BEFORE FIELD f2 DISPLAY "BEFORE FIELD f2"
AFTER FIELD f1 DISPLAY "AFTER FIELD f1" NEXT FIELD PREVIOUS
AFTER FIELD f2 DISPLAY "AFTER FIELD f2"
AFTER FIELD f3 DISPLAY "AFTER FIELD f3"
END INPUT

END MAIN