MAIN
	DEFINE f1 STRING
	CASE arg_val(1)
		WHEN 1 CALL apply_theme("7604_parallel_popup_msg_1.qxtheme") #both on focused
		WHEN 2 CALL apply_theme("7604_parallel_popup_msg_2.qxtheme") #both global
		WHEN 3 CALL apply_theme("7604_parallel_popup_msg_3.qxtheme") #global and focused at once
	END CASE
	OPEN WINDOW w WITH FORM "7604/7604_parallel_popup_msg" ATTRIBUTE(BORDER)
	INPUT BY name f1
		ON ACTION "SHOW"
			MESSAGE "MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE  MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE MESSAGE"
			ERROR "ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
	END INPUT
END MAIN