GLOBALS "8497_globals.4gl"
--PUBLIC TYPE test_type FUNCTION(v1 INT, v2 FLOAT) RETURNS STRING

MAIN
	DEFINE f test_type
	LET f = FUNCTION func
	DISPLAY f(5, 7.7)
	DISPLAY "DONE"
END MAIN

FUNCTION func(v1 INT, v2 FLOAT) RETURNS STRING
	DEFINE rv STRING
	LET rv = "|", v1, "|", v2, "|"
	RETURN rv
END FUNCTION
