MAIN
	OPEN WINDOW w WITH FORM "9435/9435_control_declarative_dialog" ATTRIBUTE(BORDER)
	DIALOG
		SUBDIALOG inp_dial1
		ON ACTION EXIT EXIT DIALOG
	END DIALOG
	DISPLAY "Done"
END MAIN

DIALOG inp_dial1()
 DEFINE f1 STRING
	INPUT BY NAME f1
		ON ACTION act_accept
            ACCEPT DIALOG
        ON ACTION act_exit
    		EXIT DIALOG
        ON ACTION act_continue
            CONTINUE DIALOG
		AFTER INPUT DISPLAY "AFTER INPUT:",f1
	END INPUT
END DIALOG