# Project: errors
# Filename: err_9215.4gl
# Created By: allu
# Creation Date: Aug 02, 2016

##############################################################################################################
# Error code:      9215 (-1143)
# Error type:      Screen Errors
# Exception class: ERROR, ANY ERROR
# Error Message:   Window w1 already open.
##############################################################################################################

#DATABASE stores_demo

MAIN

	CASE arg_val(1)
		WHEN "wec"
			CALL wec()
		WHEN "wes"
			CALL wes()
		WHEN "waec"
			CALL waec()
		WHEN "waes"
			CALL waes()
		WHEN "wegl"
			CALL wegl()
		WHEN "waegl"
			CALL waegl()
		WHEN "wecf"
			CALL wecf()
		WHEN "waecf"
			CALL waecf()
	END CASE
	DISPLAY "exit"
END MAIN


FUNCTION wec()

WHENEVER ERROR CONTINUE
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ERROR CONTINUE

END FUNCTION


FUNCTION wes()

WHENEVER ERROR STOP
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ERROR CONTINUE

END FUNCTION


FUNCTION waec()

WHENEVER ANY ERROR CONTINUE
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ANY ERROR CONTINUE

END FUNCTION

FUNCTION waes()

WHENEVER ANY ERROR STOP
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ANY ERROR CONTINUE

END FUNCTION


FUNCTION wegl()

WHENEVER ERROR GOTO lab_handling
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ERROR CONTINUE

DISPLAY "Fail"
LABEL lab_handling:
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
DISPLAY "lab_handling"
EXIT PROGRAM

END FUNCTION


FUNCTION waegl()

WHENEVER ANY ERROR GOTO lab_handling
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ANY ERROR CONTINUE

DISPLAY "Fail"
LABEL lab_handling:
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
DISPLAY "lab_handling"
EXIT PROGRAM

END FUNCTION


FUNCTION wecf()

WHENEVER ERROR CALL func_handling
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ERROR CONTINUE

END FUNCTION


FUNCTION waecf()

WHENEVER ANY ERROR CALL func_handling
	OPEN WINDOW w1 AT 1,1 WITH 10 ROWS, 40 COLUMNS
	OPEN WINDOW w1 AT 10,10 WITH 10 ROWS, 40 COLUMNS
DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
WHENEVER ANY ERROR CONTINUE

END FUNCTION


FUNCTION func_handling()

DISPLAY STATUS,SQLCA.SQLCODE,SQLCA.SQLERRD[3],SQLCA.SQLAWARN
DISPLAY "func_handling"
EXIT PROGRAM

END FUNCTION